### ISSUE TITLE
[Development] Error while  running `rspec`

### ISSUE THREAD

**Issue by amitsavani** [rikas/zoho_hub#60]
Getting following error while running `rspec` as well as `rake/spec`

```
An error occurred while loading spec_helper.
Failure/Error: raise "ERROR: #{params[:error]}" if params[:error]

RuntimeError:
  ERROR: invalid_client
# ./lib/zoho_hub.rb:40:in `setup_connection'
# ./spec/spec_helper.rb:19:in `<top (required)>'
No examples found.
No examples found.


Finished in 0.00002 seconds (files took 1.23 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

Finished in 0.00002 seconds (files took 1.23 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

**Comment by rikas** [comment]
This should be fixed by #62
